/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface HeaderPokedex {
    }
}
declare global {
    interface HTMLHeaderPokedexElement extends Components.HeaderPokedex, HTMLStencilElement {
    }
    var HTMLHeaderPokedexElement: {
        prototype: HTMLHeaderPokedexElement;
        new (): HTMLHeaderPokedexElement;
    };
    interface HTMLElementTagNameMap {
        "header-pokedex": HTMLHeaderPokedexElement;
    }
}
declare namespace LocalJSX {
    interface HeaderPokedex {
    }
    interface IntrinsicElements {
        "header-pokedex": HeaderPokedex;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "header-pokedex": LocalJSX.HeaderPokedex & JSXBase.HTMLAttributes<HTMLHeaderPokedexElement>;
        }
    }
}
